"""add trashed document table

Revision ID: 0eec43ad471d
Revises: a62e7305e752
Create Date: 2025-06-07 09:52:27.891340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eec43ad471d'
down_revision: Union[str, None] = 'a62e7305e752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('notification_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('notified_user',
    sa.Column('notified_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('notification_id', sa.BigInteger(), nullable=False),
    sa.Column('has_read', sa.Boolean(), nullable=True),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['staff_system_acc.account_id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.notification_id'], ),
    sa.PrimaryKeyConstraint('notified_id')
    )
    op.create_table('trashed_document',
    sa.Column('trashed_doc_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('original_doc_id', sa.UUID(), nullable=False),
    sa.Column('deleted_by', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff_system_acc.account_id'], ),
    sa.ForeignKeyConstraint(['original_doc_id'], ['document_record.doc_record_id'], ),
    sa.PrimaryKeyConstraint('trashed_doc_id')
    )
    op.create_index(op.f('ix_trashed_document_original_doc_id'), 'trashed_document', ['original_doc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trashed_document_original_doc_id'), table_name='trashed_document')
    op.drop_table('trashed_document')
    op.drop_table('notified_user')
    op.drop_table('notification')
    # ### end Alembic commands ###
