"""add account_holder_name in staff_system_acc

Revision ID: 177dd8111886
Revises: 5f6718a2d8a0
Create Date: 2025-05-26 17:47:33.907118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '177dd8111886'
down_revision: Union[str, None] = '5f6718a2d8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_system_acc', sa.Column('account_holder_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_system_acc', 'account_holder_name')
    # ### end Alembic commands ###
