"""update server_default time zone on models

Revision ID: 42543eb75187
Revises: da6d39e934f4
Create Date: 2025-06-11 14:43:44.259328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42543eb75187'
down_revision: Union[str, None] = 'da6d39e934f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deleted_document_doc_owner', table_name='deleted_document')
    op.create_index('ix_deleted_document_doc_owner', 'deleted_document', ['deleted_by'], unique=False)
    op.alter_column('staff_system_acc', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff_system_acc', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index('ix_deleted_document_doc_owner', table_name='deleted_document')
    op.create_index('ix_deleted_document_doc_owner', 'deleted_document', ['doc_owner_ic'], unique=False)
    # ### end Alembic commands ###
