"""Initial schema

Revision ID: 437689b362ec
Revises: initial_schema
Create Date: 2025-05-26 11:25:23.140968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '437689b362ec'
down_revision: Union[str, None] = 'initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_owner_name', sa.String(), nullable=False),
    sa.Column('doc_owner_ic', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('issuer_name', sa.String(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('hash', sa.LargeBinary(), nullable=False),
    sa.Column('signature', sa.LargeBinary(), nullable=False),
    sa.Column('verification_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_records_id'), 'document_records', ['id'], unique=False)
    op.create_table('staff',
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('ic_no', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender_enum'), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_index(op.f('ix_staff_email'), 'staff', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_email'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_document_records_id'), table_name='document_records')
    op.drop_table('document_records')
    # ### end Alembic commands ###
