"""Add default to login_session.created_at

Revision ID: 4a0e5b0ae88d
Revises: b9dac970a2a4
Create Date: 2025-06-11 15:19:02.089881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0e5b0ae88d'
down_revision: Union[str, None] = 'b9dac970a2a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deleted_document_doc_owner', table_name='deleted_document')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_deleted_document_doc_owner', 'deleted_document', ['deleted_by'], unique=False)
    # ### end Alembic commands ###
