"""Enforce not nullable on staff_system_acc fields

Revision ID: 5f6718a2d8a0
Revises: 6c706c12bee0
Create Date: 2025-05-26 17:13:52.626473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f6718a2d8a0'
down_revision: Union[str, None] = '6c706c12bee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff_system_acc', 'password_salt',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('staff_system_acc', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('staff_system_acc', 'is_super',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff_system_acc', 'is_super',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('staff_system_acc', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('staff_system_acc', 'password_salt',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
