"""add staff_system_acc and change documentrecords issuer_id to staff_account_id

Revision ID: 6c706c12bee0
Revises: 3efa05ef5bf3
Create Date: 2025-05-26 17:09:18.918325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c706c12bee0'
down_revision: Union[str, None] = '3efa05ef5bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_system_acc',
    sa.Column('account_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_salt', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_super', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('staff_id')
    )
    op.create_index('ix_document_records_doc_owner', 'document_records', ['doc_owner_name', 'doc_owner_ic'], unique=False)
    op.drop_constraint('fk_document_records_issuer', 'document_records', type_='foreignkey')
    op.create_foreign_key(None, 'document_records', 'staff_system_acc', ['issuer_id'], ['account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_records', type_='foreignkey')
    op.create_foreign_key('fk_document_records_issuer', 'document_records', 'staff', ['issuer_id'], ['staff_id'])
    op.drop_index('ix_document_records_doc_owner', table_name='document_records')
    op.drop_table('staff_system_acc')
    # ### end Alembic commands ###
