"""update server_default time zone on models

Revision ID: 896bd04e860d
Revises: 42543eb75187
Create Date: 2025-06-11 14:44:25.835345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896bd04e860d'
down_revision: Union[str, None] = '42543eb75187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deleted_document_doc_owner', table_name='deleted_document')
    op.create_index('ix_deleted_document_doc_owner', 'deleted_document', ['doc_owner_ic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deleted_document_doc_owner', table_name='deleted_document')
    op.create_index('ix_deleted_document_doc_owner', 'deleted_document', ['deleted_by'], unique=False)
    # ### end Alembic commands ###
