"""add temp_password boolean

Revision ID: 95553a31a5c7
Revises: ecac7e906859
Create Date: 2025-05-28 16:38:08.239160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95553a31a5c7'
down_revision: Union[str, None] = 'ecac7e906859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Set default to false temporarily to populate existing rows
    op.add_column(
        'staff_system_acc',
        sa.Column('temp_password', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )

    # Now set default to true for future inserts
    op.alter_column('staff_system_acc', 'temp_password', server_default=sa.text('true'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_system_acc', 'temp_password')
    # ### end Alembic commands ###
