"""add has_received for tracking if notification has been received

Revision ID: ab901d16ba9e
Revises: fa0a14552a28
Create Date: 2025-06-07 16:37:03.351427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab901d16ba9e'
down_revision: Union[str, None] = 'fa0a14552a28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notified_user', sa.Column('has_received', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notified_user', 'has_received')
    # ### end Alembic commands ###
