"""remove trashed_document table, add fields in doocument_record for soft delete

Revision ID: c0c77976b39f
Revises: c7b469c76f9d
Create Date: 2025-06-07 10:29:14.746878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0c77976b39f'
down_revision: Union[str, None] = 'c7b469c76f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trashed_document_original_doc_id', table_name='trashed_document')
    op.drop_table('trashed_document')
    op.add_column('document_record', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('document_record', sa.Column('deleted_by', sa.BigInteger(), nullable=True))
    op.add_column('document_record', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index('ix_document_record_is_deleted', 'document_record', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'document_record', 'staff_system_acc', ['deleted_by'], ['account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_record', type_='foreignkey')
    op.drop_index('ix_document_record_is_deleted', table_name='document_record')
    op.drop_column('document_record', 'deleted_at')
    op.drop_column('document_record', 'deleted_by')
    op.drop_column('document_record', 'is_deleted')
    op.create_table('trashed_document',
    sa.Column('trashed_doc_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('original_doc_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deleted_by', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff_system_acc.account_id'], name='trashed_document_deleted_by_fkey'),
    sa.ForeignKeyConstraint(['original_doc_id'], ['document_record.doc_record_id'], name='trashed_document_original_doc_id_fkey'),
    sa.PrimaryKeyConstraint('trashed_doc_id', name='trashed_document_pkey')
    )
    op.create_index('ix_trashed_document_original_doc_id', 'trashed_document', ['original_doc_id'], unique=False)
    # ### end Alembic commands ###
