"""rename notified_at to received_at, and remove the default value

Revision ID: d029e9a62df6
Revises: ab901d16ba9e
Create Date: 2025-06-08 12:14:02.576266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd029e9a62df6'
down_revision: Union[str, None] = 'ab901d16ba9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notified_user', sa.Column('received_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('notified_user', 'notified_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notified_user', sa.Column('notified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('notified_user', 'received_at')
    # ### end Alembic commands ###
