"""add deleted_document table

Revision ID: da6d39e934f4
Revises: b00522d945c8
Create Date: 2025-06-11 14:10:28.752399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6d39e934f4'
down_revision: Union[str, None] = 'b00522d945c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_document',
    sa.Column('deleted_doc_id', sa.BigInteger(), nullable=False),
    sa.Column('doc_owner_ic', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('deleted_by', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff_system_acc.account_id'], ),
    sa.ForeignKeyConstraint(['doc_owner_ic'], ['owner.owner_ic_no'], ),
    sa.PrimaryKeyConstraint('deleted_doc_id')
    )
    op.create_index(op.f('ix_deleted_document_deleted_by'), 'deleted_document', ['deleted_by'], unique=False)
    op.create_index('ix_deleted_document_doc_owner', 'deleted_document', ['doc_owner_ic'], unique=False)
    op.create_index(op.f('ix_deleted_document_doc_owner_ic'), 'deleted_document', ['doc_owner_ic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deleted_document_doc_owner_ic'), table_name='deleted_document')
    op.drop_index('ix_deleted_document_doc_owner', table_name='deleted_document')
    op.drop_index(op.f('ix_deleted_document_deleted_by'), table_name='deleted_document')
    op.drop_table('deleted_document')
    # ### end Alembic commands ###
