"""add login session table

Revision ID: dce103f18742
Revises: 9f10afa18f1d
Create Date: 2025-05-27 17:03:51.224319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce103f18742'
down_revision: Union[str, None] = '9f10afa18f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_session', sa.Column('account_id', sa.Integer(), nullable=False))
    op.drop_constraint('login_session_user_id_fkey', 'login_session', type_='foreignkey')
    op.create_foreign_key(None, 'login_session', 'staff_system_acc', ['account_id'], ['account_id'], ondelete='CASCADE')
    op.drop_column('login_session', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_session', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'login_session', type_='foreignkey')
    op.create_foreign_key('login_session_user_id_fkey', 'login_session', 'staff_system_acc', ['user_id'], ['account_id'], ondelete='CASCADE')
    op.drop_column('login_session', 'account_id')
    # ### end Alembic commands ###
