"""add profile image in staff_system_acc

Revision ID: ecac7e906859
Revises: dce103f18742
Create Date: 2025-05-27 22:35:55.624686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecac7e906859'
down_revision: Union[str, None] = 'dce103f18742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_system_acc', sa.Column('profile_img', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_system_acc', 'profile_img')
    # ### end Alembic commands ###
